# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb3221922ade58b21774a4624d3b84d7a4aa35b5270e287b7f60d205d928ce8067e0687638554bcc9606a272e5186d07a8e8400bb90ff44840220afd3fc60f5e

test:
  secret_key_base: eb9af7285ef8cabc2e1c028001d3cd2396dd2d78aa68e0bc9416f025a4e7beaab6495a3ec731a9178945aa4b2175a39f261b2e3d7811438cd5c3b7b5786d5135

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
